import type { AllowedLanguages } from './AllowedLanguages.ts';

export enum ShowType {
    EventoAziendale = 'Evento Aziendale',
    Matrimonio = 'Matrimonio',
    Party = 'Party',
    Compleanno = 'Compleanno',
    EventoClub = 'Evento Club',
    Festival = 'Festival',
    CerimoniaReligiosa = 'Cerimonia Religiosa',
    Cerimonia = 'Cerimonia',
    EventoStagionale = 'Evento Stagionale',
    MusicaDambiente = 'Musica D\'ambiente',
    FestaPerBambini = 'Festa Per Bambini',
    EventoInBarRistorante = 'Evento In Bar / Ristorante',
    EventoInHotel = 'Evento In Hotel',
    CasaDiRiposo = 'Casa Di Riposo',
    Evento = 'Evento'
}

export const ShowTypeVlues: { [key in ShowType]: number } = {
    [ShowType.EventoAziendale]: 1,
    [ShowType.Matrimonio]: 2,
    [ShowType.Party]: 3,
    [ShowType.Compleanno]: 4,
    [ShowType.EventoClub]: 6,
    [ShowType.Festival]: 7,
    [ShowType.CerimoniaReligiosa]: 8,
    [ShowType.Cerimonia]: 9,
    [ShowType.EventoStagionale]: 13,
    [ShowType.MusicaDambiente]: 16,
    [ShowType.FestaPerBambini]: 17,
    [ShowType.EventoInBarRistorante]: 18,
    [ShowType.EventoInHotel]: 19,
    [ShowType.CasaDiRiposo]: 20,
    [ShowType.Evento]: 999
};

export enum ArtistType {
    Band = 'Band',
    Musicista = 'Musicista',
    DJ = 'DJ',
    Ensemble = 'Ensemble',
    Intrattenitore = 'Intrattenitore',
    Mago = 'Mago',
    Speaker = 'Speaker',
    Dancer = 'Dancer',
    Fotografi = 'Fotografi',
    NoleggioPerEventi = 'Noleggio per eventi',
    ServiziPerEventi = 'Servizi per eventi',
    TeamBuilding = 'Team building',
    Packages = 'Packages'
}

export const ArtistTypeValues: { [key in ArtistType]: number } = {
    [ArtistType.Band]: 1,
    [ArtistType.Musicista]: 2,
    [ArtistType.DJ]: 3,
    [ArtistType.Ensemble]: 4,
    [ArtistType.Intrattenitore]: 5,
    [ArtistType.Mago]: 6,
    [ArtistType.Speaker]: 7,
    [ArtistType.Dancer]: 8,
    [ArtistType.Fotografi]: 9,
    [ArtistType.NoleggioPerEventi]: 10,
    [ArtistType.ServiziPerEventi]: 11,
    [ArtistType.TeamBuilding]: 12,
    [ArtistType.Packages]: 13
};

export enum ArtistSubType {
    BigBand = 'Big Band',
    SuonatoreDiSteelDrum = 'Suonatore di Steel Drum',
    Karaoke = 'Karaoke',
    Originale = 'Originale',
    Cover = 'Cover',
    Tribute = 'Tribute',
    OneManBand = 'One Man Band',
    Radio = 'Radio',
    Lounge = 'Lounge',
    MusicaAcustica = 'Musica Acustica',
    GruppoACappella = 'Gruppo a Cappella',
    Quartetto = 'Quartetto',
    TrioDarchi = 'Trio d\'archi',
    Guggen = 'Guggen',
    BrassBand = 'Brass Band',
    OrchestraDaCamera = 'Orchestra da camera',
    DuoClassico = 'Duo Classico',
    Orchestra = 'Orchestra',
    Coro = 'Coro',
    Percussionista = 'Percussionista',
    Sassofonista = 'Sassofonista',
    Pianista = 'Pianista',
    CantanteVoceMaschile = 'Cantante voce maschile',
    Violinista = 'Violinista',
    Flautista = 'Flautista',
    Chitarrista = 'Chitarrista',
    Violoncellista = 'Violoncellista',
    Vocalist = 'Vocalist',
    Tastierista = 'Tastierista',
    Organista = 'Organista',
    Crooner = 'Crooner',
    Arpista = 'Arpista',
    Rapper = 'Rapper',
    Trombettista = 'Trombettista',
    Club = 'Club',
    Clown = 'Clown',
    Comico = 'Comico',
    ScultoreDiPalloncini = 'Scultore di Palloncini',
    FacePainter = 'Face Painter',
    Giocoliere = 'Giocoliere',
    Walkacts = 'Walkacts',
    FireJuggler = 'Fire Juggler',
    Caricaturista = 'Caricaturista',
    BabboNatale = 'Babbo Natale',
    BambolaVivente = 'Bambola Vivente',
    Prestigiatore = 'Prestigiatore',
    Mentalista = 'Mentalista',
    MagiaPerBambini = 'Magia per Bambini',
    Presentatore = 'Presentatore',
    Moderatore = 'Moderatore',
    AttoreAttrice = 'Attore / Attrice',
    BallerinoBallerinaHula = 'Ballerino / Ballerina Hula',
    GruppoDiDanza = 'Gruppo di Danza',
    BallerinoBallerinaCountry = 'Ballerino / Ballerina Country',
    BallerinoBallerinaHipHop = 'Ballerino / Ballerina Hip Hop',
    BallerinoBallerinaTipTap = 'Ballerino / Ballerina Tip Tap',
    BallerinoBallerinaFlamenco = 'Ballerino / Ballerina Flamenco',
    BallerinoBallerinaTango = 'Ballerino / Ballerina Tango',
    BallerinoBallerinaMusicaLatina = 'Ballerino / Ballerina Musica Latina',
    Vintage = 'Vintage',
    DanzatriceDelVentre = 'Danzatrice del Ventre',
    Altro = 'Altro',
    Ventriloquo = 'Ventriloquo',
    Acrobati = 'Acrobati',
    Cornamusa = 'Cornamusa',
    CornoDelleAlpi = 'Corno delle alpi',
    Armonica = 'Armonica',
    Corno = 'Corno',
    VJ = 'VJ',
    OratoreAtletica = 'Oratore (Atletica)',
    OratoreBusiness = 'Oratore (Business)',
    OratoreCelebrita = 'Oratore (Celebrità)',
    OratoreAziendale = 'Oratore (Aziendale)',
    Ispiratore = 'Ispiratore',
    Motivatore = 'Motivatore',
    CommentatoreSportivo = 'Commentatore Sportivo',
    Cabaret = 'Cabaret',
    Sosia = 'Sosia',
    Mariachi = 'Mariachi',
    Percussioni = 'Percussioni',
    Legni = 'Legni',
    Duo = 'Duo',
    Trio = 'Trio',
    FlautoDiPan = 'Flauto di Pan',
    PianoBar = 'Piano Bar',
    Fisarmonica = 'Fisarmonica',
    BodyPainter = 'Body Painter',
    QuartettoDarchiESimili = 'Quartetto d\'archi e simili',
    PartyDJ = 'Party DJ',
    DJPerSottofondo = 'DJ per sottofondo',
    DJConStrumentiDalVivo = 'DJ con strumenti dal vivo',
    DJConCantante = 'DJ con cantante',
    DJConKaraoke = 'DJ con karaoke',
    PopRockPartyband = 'Pop-Rock Partyband',
    SchlagerOldies = 'Schlager & Oldies',
    BandDiGalaOrchestraDaBallo = 'Band di Gala / Orchestra da ballo',
    RockabillyPartyband = 'Rockabilly Partyband',
    PartybandIrlandese = 'Partyband Irlandese',
    CountryPartyband = 'Country Partyband',
    PartybandLatinoAmericana = 'Partyband Latino-americana',
    JazzBand = 'Jazz Band',
    VolkstumlicheMusik = 'Volkstümliche Musik',
    MusicaTicinese = 'Musica Ticinese',
    MusicaTedesca = 'Musica Tedesca',
    MusicaItaliana = 'Musica Italiana',
    SemiAcousticDuoTrioVoceEChitarra = 'Semi- & Acoustic duo/trio voce e chitarra',
    SemiAcousticDuoTrioVoceEPiano = 'Semi- & Acoustic duo/trio voce & piano',
    DuoTrioAcoustiqueInstrumental = 'Duo/trio acoustique instrumental',
    VoceEChitarraSolo = 'Voce e chitarra (solo)',
    VoceEPianoforteSolo = 'Voce e pianoforte (solo)',
    Alleinunterhalter = 'Alleinunterhalter',
    CantanteVoceFemminile = 'Cantante voce femminile',
    Fotografo = 'Fotografo',
    FotografoPerMatrimonio = 'Fotografo per matrimonio',
    Videomaker = 'Videomaker',
    VideomakerMatrimoni = 'Videomaker matrimoni',
    CastelliGonfiabili = 'Castelli gonfiabili',
    GonfiabiliPerFeste = 'Gonfiabili per feste',
    NoleggioDiCabineFotografiche = 'Noleggio di cabine fotografiche',
    Barista = 'Barista',
    Catering = 'Catering',
    FoodTrucks = 'Food Trucks',
    Sommelier = 'Sommelier',
    PianificatoreDiEventi = 'Pianificatore di eventi',
    WeddingPlanner = 'Wedding Planner',
    LimousinePerEventi = 'Limousine per eventi',
    BusPerEventi = 'Bus per eventi',
    SportEGiochi = 'Sport e giochi',
    EsperienzeNellaNatura = 'Esperienze nella natura',
    EventoPerTeam = 'Evento per team',
    Esperienza = 'Esperienza',
    Packages = 'Packages'
}

export const ArtistSubTypeValues: { [key in ArtistSubType]: number } = {
    [ArtistSubType.BigBand]: 1,
    [ArtistSubType.SuonatoreDiSteelDrum]: 2,
    [ArtistSubType.Karaoke]: 3,
    [ArtistSubType.Originale]: 4,
    [ArtistSubType.Cover]: 5,
    [ArtistSubType.Tribute]: 6,
    [ArtistSubType.OneManBand]: 7,
    [ArtistSubType.Radio]: 8,
    [ArtistSubType.Lounge]: 9,
    [ArtistSubType.MusicaAcustica]: 10,
    [ArtistSubType.GruppoACappella]: 11,
    [ArtistSubType.Quartetto]: 12,
    [ArtistSubType.TrioDarchi]: 13,
    [ArtistSubType.Guggen]: 14,
    [ArtistSubType.BrassBand]: 15,
    [ArtistSubType.OrchestraDaCamera]: 16,
    [ArtistSubType.DuoClassico]: 17,
    [ArtistSubType.Orchestra]: 18,
    [ArtistSubType.Coro]: 19,
    [ArtistSubType.Percussionista]: 20,
    [ArtistSubType.Sassofonista]: 21,
    [ArtistSubType.Pianista]: 22,
    [ArtistSubType.CantanteVoceMaschile]: 23,
    [ArtistSubType.Violinista]: 24,
    [ArtistSubType.Flautista]: 25,
    [ArtistSubType.Chitarrista]: 26,
    [ArtistSubType.Violoncellista]: 27,
    [ArtistSubType.Vocalist]: 28,
    [ArtistSubType.Tastierista]: 29,
    [ArtistSubType.Organista]: 30,
    [ArtistSubType.Crooner]: 31,
    [ArtistSubType.Arpista]: 32,
    [ArtistSubType.Rapper]: 33,
    [ArtistSubType.Trombettista]: 34,
    [ArtistSubType.Club]: 35,
    [ArtistSubType.Clown]: 36,
    [ArtistSubType.Comico]: 37,
    [ArtistSubType.ScultoreDiPalloncini]: 38,
    [ArtistSubType.FacePainter]: 39,
    [ArtistSubType.Giocoliere]: 40,
    [ArtistSubType.Walkacts]: 41,
    [ArtistSubType.FireJuggler]: 42,
    [ArtistSubType.Caricaturista]: 43,
    [ArtistSubType.BabboNatale]: 44,
    [ArtistSubType.BambolaVivente]: 45,
    [ArtistSubType.Prestigiatore]: 46,
    [ArtistSubType.Mentalista]: 47,
    [ArtistSubType.MagiaPerBambini]: 48,
    [ArtistSubType.Presentatore]: 49,
    [ArtistSubType.Moderatore]: 50,
    [ArtistSubType.AttoreAttrice]: 51,
    [ArtistSubType.BallerinoBallerinaHula]: 54,
    [ArtistSubType.GruppoDiDanza]: 55,
    [ArtistSubType.BallerinoBallerinaCountry]: 56,
    [ArtistSubType.BallerinoBallerinaHipHop]: 57,
    [ArtistSubType.BallerinoBallerinaTipTap]: 58,
    [ArtistSubType.BallerinoBallerinaFlamenco]: 59,
    [ArtistSubType.BallerinoBallerinaTango]: 60,
    [ArtistSubType.BallerinoBallerinaMusicaLatina]: 61,
    [ArtistSubType.Vintage]: 62,
    [ArtistSubType.DanzatriceDelVentre]: 63,
    [ArtistSubType.Altro]: 64,
    [ArtistSubType.Ventriloquo]: 65,
    [ArtistSubType.Acrobati]: 66,
    [ArtistSubType.Cornamusa]: 67,
    [ArtistSubType.CornoDelleAlpi]: 68,
    [ArtistSubType.Armonica]: 69,
    [ArtistSubType.Corno]: 70,
    [ArtistSubType.VJ]: 71,
    [ArtistSubType.OratoreAtletica]: 72,
    [ArtistSubType.OratoreBusiness]: 73,
    [ArtistSubType.OratoreCelebrita]: 74,
    [ArtistSubType.OratoreAziendale]: 75,
    [ArtistSubType.Ispiratore]: 76,
    [ArtistSubType.Motivatore]: 77,
    [ArtistSubType.CommentatoreSportivo]: 78,
    [ArtistSubType.Cabaret]: 79,
    [ArtistSubType.Sosia]: 80,
    [ArtistSubType.Mariachi]: 81,
    [ArtistSubType.Percussioni]: 82,
    [ArtistSubType.Legni]: 83,
    [ArtistSubType.Duo]: 84,
    [ArtistSubType.Trio]: 85,
    [ArtistSubType.FlautoDiPan]: 86,
    [ArtistSubType.PianoBar]: 87,
    [ArtistSubType.Fisarmonica]: 88,
    [ArtistSubType.BodyPainter]: 89,
    [ArtistSubType.QuartettoDarchiESimili]: 90,
    [ArtistSubType.PartyDJ]: 91,
    [ArtistSubType.DJPerSottofondo]: 92,
    [ArtistSubType.DJConStrumentiDalVivo]: 93,
    [ArtistSubType.DJConCantante]: 94,
    [ArtistSubType.DJConKaraoke]: 95,
    [ArtistSubType.PopRockPartyband]: 96,
    [ArtistSubType.SchlagerOldies]: 97,
    [ArtistSubType.BandDiGalaOrchestraDaBallo]: 98,
    [ArtistSubType.RockabillyPartyband]: 99,
    [ArtistSubType.PartybandIrlandese]: 100,
    [ArtistSubType.CountryPartyband]: 101,
    [ArtistSubType.PartybandLatinoAmericana]: 102,
    [ArtistSubType.JazzBand]: 103,
    [ArtistSubType.VolkstumlicheMusik]: 104,
    [ArtistSubType.MusicaTicinese]: 105,
    [ArtistSubType.MusicaTedesca]: 106,
    [ArtistSubType.MusicaItaliana]: 107,
    [ArtistSubType.SemiAcousticDuoTrioVoceEChitarra]: 108,
    [ArtistSubType.SemiAcousticDuoTrioVoceEPiano]: 109,
    [ArtistSubType.DuoTrioAcoustiqueInstrumental]: 110,
    [ArtistSubType.VoceEChitarraSolo]: 111,
    [ArtistSubType.VoceEPianoforteSolo]: 112,
    [ArtistSubType.Alleinunterhalter]: 113,
    [ArtistSubType.CantanteVoceFemminile]: 114,
    [ArtistSubType.Fotografo]: 115,
    [ArtistSubType.FotografoPerMatrimonio]: 116,
    [ArtistSubType.Videomaker]: 118,
    [ArtistSubType.VideomakerMatrimoni]: 119,
    [ArtistSubType.CastelliGonfiabili]: 120,
    [ArtistSubType.GonfiabiliPerFeste]: 121,
    [ArtistSubType.NoleggioDiCabineFotografiche]: 122,
    [ArtistSubType.Barista]: 123,
    [ArtistSubType.Catering]: 124,
    [ArtistSubType.FoodTrucks]: 125,
    [ArtistSubType.Sommelier]: 126,
    [ArtistSubType.PianificatoreDiEventi]: 127,
    [ArtistSubType.WeddingPlanner]: 128,
    [ArtistSubType.LimousinePerEventi]: 129,
    [ArtistSubType.BusPerEventi]: 130,
    [ArtistSubType.SportEGiochi]: 131,
    [ArtistSubType.EsperienzeNellaNatura]: 132,
    [ArtistSubType.EventoPerTeam]: 133,
    [ArtistSubType.Esperienza]: 134,
    [ArtistSubType.Packages]: 135
};

export enum ArtistGenre {
    Pop = 'Pop',
    Rock = 'Rock',
    Electro = 'Electro',
    RnB = 'R&B',
    Metal = 'Metal',
    HouseTechno = 'House/Techno',
    HipHop = 'Hip Hop',
    Punk = 'Punk',
    DiscoDance = 'Disco Dance',
    Rap = 'Rap',
    Alternative = 'Alternative',
    Jazz = 'Jazz',
    Latin = 'Latin',
    Folk = 'Folk',
    Classical = 'Classical',
    Reggae = 'Reggae',
    Funk = 'Funk',
    ChristianGospel = 'Christian/Gospel',
    Country = 'Country',
    Ska = 'Ska',
    WorldMusic = 'World Music',
    Blues = 'Blues',
    Other = 'Other',
    Lounge = 'Lounge',
    Soul = 'Soul',
    Swing = 'Swing',
    Rockabilly = 'Rockabilly',
    Tanzmusik = 'Tanzmusik',
    VolkstumlicheMusik = 'Volkstümliche Musik',
    Schlager = 'Schlager',
    Oldiebands = 'Oldiebands',
    Celtic = 'Celtic',
    Irish = 'Irish',
    Twenties = '20s',
    Thirties = '30s',
    Forties = '40s',
    Fifties = '50s',
    Sixties = '60s',
    Seventies = '70s',
    Eighties = '80s',
    Nineties = '90s',
    African = 'African',
    Ambient = 'Ambient',
    Flamenco = 'Flamenco',
    Fusion = 'Fusion',
    Greek = 'Greek',
    Groove = 'Groove',
    Grunge = 'Grunge',
    Gypsy = 'Gypsy',
    Hawaiian = 'Hawaiian',
    HonkyTonk = 'Honky Tonk',
    Indie = 'Indie',
    Industrial = 'Industrial',
    Italian = 'Italian',
    Jam = 'Jam',
    MiddleEastern = 'Middle Eastern',
    NewAge = 'New Age',
    Polka = 'Polka',
    Ragtime = 'Ragtime',
    SalsaMerengue = 'Salsa/Merengue',
    SouthernRock = 'Southern Rock',
    SurfBeach = 'Surf/Beach',
    Bluegrass = 'Bluegrass',
    Brazilian = 'Brazilian',
    Carribean = 'Carribean',
    Cuban = 'Cuban',
    Tango = 'Tango',
    Christmas = 'Christmas',
    Meditational = 'Meditational',
    Opera = 'Opera',
    ChamberMusic = 'Chamber Music',
    KidsMusic = 'Kids Music',
    Ticinese = 'Ticinese',
    Jodel = 'Jodel',
    HardRock = 'Hard Rock',
    Mundart = 'Mundart'
}

export const ArtistGenreMapping: { [key in ArtistGenre]: number } = {
    [ArtistGenre.Pop]: 1,
    [ArtistGenre.Rock]: 2,
    [ArtistGenre.Electro]: 3,
    [ArtistGenre.RnB]: 4,
    [ArtistGenre.Metal]: 5,
    [ArtistGenre.HouseTechno]: 6,
    [ArtistGenre.HipHop]: 7,
    [ArtistGenre.Punk]: 8,
    [ArtistGenre.DiscoDance]: 9,
    [ArtistGenre.Rap]: 10,
    [ArtistGenre.Alternative]: 11,
    [ArtistGenre.Jazz]: 12,
    [ArtistGenre.Latin]: 13,
    [ArtistGenre.Folk]: 14,
    [ArtistGenre.Classical]: 15,
    [ArtistGenre.Reggae]: 16,
    [ArtistGenre.Funk]: 17,
    [ArtistGenre.ChristianGospel]: 18,
    [ArtistGenre.Country]: 19,
    [ArtistGenre.Ska]: 20,
    [ArtistGenre.WorldMusic]: 21,
    [ArtistGenre.Blues]: 22,
    [ArtistGenre.Other]: 23,
    [ArtistGenre.Lounge]: 24,
    [ArtistGenre.Soul]: 25,
    [ArtistGenre.Swing]: 26,
    [ArtistGenre.Rockabilly]: 27,
    [ArtistGenre.Tanzmusik]: 28,
    [ArtistGenre.VolkstumlicheMusik]: 29,
    [ArtistGenre.Schlager]: 30,
    [ArtistGenre.Oldiebands]: 31,
    [ArtistGenre.Celtic]: 32,
    [ArtistGenre.Irish]: 33,
    [ArtistGenre.Twenties]: 34,
    [ArtistGenre.Thirties]: 35,
    [ArtistGenre.Forties]: 36,
    [ArtistGenre.Fifties]: 37,
    [ArtistGenre.Sixties]: 38,
    [ArtistGenre.Seventies]: 39,
    [ArtistGenre.Eighties]: 40,
    [ArtistGenre.Nineties]: 41,
    [ArtistGenre.African]: 42,
    [ArtistGenre.Ambient]: 43,
    [ArtistGenre.Flamenco]: 44,
    [ArtistGenre.Fusion]: 45,
    [ArtistGenre.Greek]: 46,
    [ArtistGenre.Groove]: 47,
    [ArtistGenre.Grunge]: 48,
    [ArtistGenre.Gypsy]: 49,
    [ArtistGenre.Hawaiian]: 50,
    [ArtistGenre.HonkyTonk]: 51,
    [ArtistGenre.Indie]: 52,
    [ArtistGenre.Industrial]: 53,
    [ArtistGenre.Italian]: 54,
    [ArtistGenre.Jam]: 55,
    [ArtistGenre.MiddleEastern]: 56,
    [ArtistGenre.NewAge]: 58,
    [ArtistGenre.Polka]: 59,
    [ArtistGenre.Ragtime]: 60,
    [ArtistGenre.SalsaMerengue]: 61,
    [ArtistGenre.SouthernRock]: 62,
    [ArtistGenre.SurfBeach]: 63,
    [ArtistGenre.Bluegrass]: 64,
    [ArtistGenre.Brazilian]: 65,
    [ArtistGenre.Carribean]: 66,
    [ArtistGenre.Cuban]: 67,
    [ArtistGenre.Tango]: 68,
    [ArtistGenre.Christmas]: 69,
    [ArtistGenre.Meditational]: 70,
    [ArtistGenre.Opera]: 71,
    [ArtistGenre.ChamberMusic]: 72,
    [ArtistGenre.KidsMusic]: 73,
    [ArtistGenre.Ticinese]: 74,
    [ArtistGenre.Jodel]: 75,
    [ArtistGenre.HardRock]: 76,
    [ArtistGenre.Mundart]: 77
};

export enum FilterType {
    LANGUAGE = 'LANGUAGE',
    SHOW_TYPE = 'SHOW_TYPE',
    ARTIST_TYPE = 'ARTIST_TYPE',
    ARTIST_SUB_TYPE = 'ARTIST_SUB_TYPE',
    ARTIST_GENRE = 'ARTIST_GENRE'
}

export type LanguageFilter = {
	f: FilterType.LANGUAGE;
	k: AllowedLanguages;
    v: AllowedLanguages;
    i: boolean;
};

export type ShowTypeFilter = {
	f: FilterType.SHOW_TYPE;
	k: number;
    v: ShowType;
    i: boolean;
};

export type ArtistTypeFilter = {
	f: FilterType.ARTIST_TYPE;
	k: number;
    v: ArtistType;
    i: boolean;
};

export type ArtistSubTypeFilter = {
	f: FilterType.ARTIST_SUB_TYPE;
	k: number;
    v: ArtistSubType;
    i: boolean;
};

export type ArtistGenreFilter = {
	f: FilterType.ARTIST_GENRE;
	k: number;
    v: ArtistGenre;
    i: boolean;
};

export type Filter = LanguageFilter | ShowTypeFilter | ArtistTypeFilter | ArtistSubTypeFilter | ArtistGenreFilter;