import type { AllowedLanguages } from './AllowedLanguages.ts';

export enum ShowTypeEnum {
    EventoAziendale = 'Evento Aziendale',
    Matrimonio = 'Matrimonio',
    Party = 'Party',
    Compleanno = 'Compleanno',
    EventoClub = 'Evento Club',
    Festival = 'Festival',
    CerimoniaReligiosa = 'Cerimonia Religiosa',
    Cerimonia = 'Cerimonia',
    EventoStagionale = 'Evento Stagionale',
    MusicaDambiente = 'Musica D\'ambiente',
    FestaPerBambini = 'Festa Per Bambini',
    EventoInBarRistorante = 'Evento In Bar / Ristorante',
    EventoInHotel = 'Evento In Hotel',
    CasaDiRiposo = 'Casa Di Riposo',
    Evento = 'Evento'
};

export type ShowType = `${ShowTypeEnum}`;

export const ShowTypeVlues: { [key in ShowTypeEnum]: number } = {
    [ShowTypeEnum.EventoAziendale]: 1,
    [ShowTypeEnum.Matrimonio]: 2,
    [ShowTypeEnum.Party]: 3,
    [ShowTypeEnum.Compleanno]: 4,
    [ShowTypeEnum.EventoClub]: 6,
    [ShowTypeEnum.Festival]: 7,
    [ShowTypeEnum.CerimoniaReligiosa]: 8,
    [ShowTypeEnum.Cerimonia]: 9,
    [ShowTypeEnum.EventoStagionale]: 13,
    [ShowTypeEnum.MusicaDambiente]: 16,
    [ShowTypeEnum.FestaPerBambini]: 17,
    [ShowTypeEnum.EventoInBarRistorante]: 18,
    [ShowTypeEnum.EventoInHotel]: 19,
    [ShowTypeEnum.CasaDiRiposo]: 20,
    [ShowTypeEnum.Evento]: 999
};

export enum ArtistTypeEnum {
    Band = 'Band',
    Musicista = 'Musicista',
    DJ = 'DJ',
    Ensemble = 'Ensemble',
    Intrattenitore = 'Intrattenitore',
    Mago = 'Mago',
    Speaker = 'Speaker',
    Dancer = 'Dancer',
    Fotografi = 'Fotografi',
    NoleggioPerEventi = 'Noleggio per eventi',
    ServiziPerEventi = 'Servizi per eventi',
    TeamBuilding = 'Team building',
    Packages = 'Packages'
};

export type ArtistType = `${ArtistTypeEnum}`;

export const ArtistTypeValues: { [key in ArtistType]: number } = {
    [ArtistTypeEnum.Band]: 1,
    [ArtistTypeEnum.Musicista]: 2,
    [ArtistTypeEnum.DJ]: 3,
    [ArtistTypeEnum.Ensemble]: 4,
    [ArtistTypeEnum.Intrattenitore]: 5,
    [ArtistTypeEnum.Mago]: 6,
    [ArtistTypeEnum.Speaker]: 7,
    [ArtistTypeEnum.Dancer]: 8,
    [ArtistTypeEnum.Fotografi]: 9,
    [ArtistTypeEnum.NoleggioPerEventi]: 10,
    [ArtistTypeEnum.ServiziPerEventi]: 11,
    [ArtistTypeEnum.TeamBuilding]: 12,
    [ArtistTypeEnum.Packages]: 13
};

export enum ArtistSubTypeEnum {
    BigBand = 'Big Band',
    SuonatoreDiSteelDrum = 'Suonatore di Steel Drum',
    Karaoke = 'Karaoke',
    Originale = 'Originale',
    Cover = 'Cover',
    Tribute = 'Tribute',
    OneManBand = 'One Man Band',
    Radio = 'Radio',
    Lounge = 'Lounge',
    MusicaAcustica = 'Musica Acustica',
    GruppoACappella = 'Gruppo a Cappella',
    Quartetto = 'Quartetto',
    TrioDarchi = 'Trio d\'archi',
    Guggen = 'Guggen',
    BrassBand = 'Brass Band',
    OrchestraDaCamera = 'Orchestra da camera',
    DuoClassico = 'Duo Classico',
    Orchestra = 'Orchestra',
    Coro = 'Coro',
    Percussionista = 'Percussionista',
    Sassofonista = 'Sassofonista',
    Pianista = 'Pianista',
    CantanteVoceMaschile = 'Cantante voce maschile',
    Violinista = 'Violinista',
    Flautista = 'Flautista',
    Chitarrista = 'Chitarrista',
    Violoncellista = 'Violoncellista',
    Vocalist = 'Vocalist',
    Tastierista = 'Tastierista',
    Organista = 'Organista',
    Crooner = 'Crooner',
    Arpista = 'Arpista',
    Rapper = 'Rapper',
    Trombettista = 'Trombettista',
    Club = 'Club',
    Clown = 'Clown',
    Comico = 'Comico',
    ScultoreDiPalloncini = 'Scultore di Palloncini',
    FacePainter = 'Face Painter',
    Giocoliere = 'Giocoliere',
    Walkacts = 'Walkacts',
    FireJuggler = 'Fire Juggler',
    Caricaturista = 'Caricaturista',
    BabboNatale = 'Babbo Natale',
    BambolaVivente = 'Bambola Vivente',
    Prestigiatore = 'Prestigiatore',
    Mentalista = 'Mentalista',
    MagiaPerBambini = 'Magia per Bambini',
    Presentatore = 'Presentatore',
    Moderatore = 'Moderatore',
    AttoreAttrice = 'Attore / Attrice',
    BallerinoBallerinaHula = 'Ballerino / Ballerina Hula',
    GruppoDiDanza = 'Gruppo di Danza',
    BallerinoBallerinaCountry = 'Ballerino / Ballerina Country',
    BallerinoBallerinaHipHop = 'Ballerino / Ballerina Hip Hop',
    BallerinoBallerinaTipTap = 'Ballerino / Ballerina Tip Tap',
    BallerinoBallerinaFlamenco = 'Ballerino / Ballerina Flamenco',
    BallerinoBallerinaTango = 'Ballerino / Ballerina Tango',
    BallerinoBallerinaMusicaLatina = 'Ballerino / Ballerina Musica Latina',
    Vintage = 'Vintage',
    DanzatriceDelVentre = 'Danzatrice del Ventre',
    Altro = 'Altro',
    Ventriloquo = 'Ventriloquo',
    Acrobati = 'Acrobati',
    Cornamusa = 'Cornamusa',
    CornoDelleAlpi = 'Corno delle alpi',
    Armonica = 'Armonica',
    Corno = 'Corno',
    VJ = 'VJ',
    OratoreAtletica = 'Oratore (Atletica)',
    OratoreBusiness = 'Oratore (Business)',
    OratoreCelebrita = 'Oratore (Celebrità)',
    OratoreAziendale = 'Oratore (Aziendale)',
    Ispiratore = 'Ispiratore',
    Motivatore = 'Motivatore',
    CommentatoreSportivo = 'Commentatore Sportivo',
    Cabaret = 'Cabaret',
    Sosia = 'Sosia',
    Mariachi = 'Mariachi',
    Percussioni = 'Percussioni',
    Legni = 'Legni',
    Duo = 'Duo',
    Trio = 'Trio',
    FlautoDiPan = 'Flauto di Pan',
    PianoBar = 'Piano Bar',
    Fisarmonica = 'Fisarmonica',
    BodyPainter = 'Body Painter',
    QuartettoDarchiESimili = 'Quartetto d\'archi e simili',
    PartyDJ = 'Party DJ',
    DJPerSottofondo = 'DJ per sottofondo',
    DJConStrumentiDalVivo = 'DJ con strumenti dal vivo',
    DJConCantante = 'DJ con cantante',
    DJConKaraoke = 'DJ con karaoke',
    PopRockPartyband = 'Pop-Rock Partyband',
    SchlagerOldies = 'Schlager & Oldies',
    BandDiGalaOrchestraDaBallo = 'Band di Gala / Orchestra da ballo',
    RockabillyPartyband = 'Rockabilly Partyband',
    PartybandIrlandese = 'Partyband Irlandese',
    CountryPartyband = 'Country Partyband',
    PartybandLatinoAmericana = 'Partyband Latino-americana',
    JazzBand = 'Jazz Band',
    VolkstumlicheMusik = 'Volkstümliche Musik',
    MusicaTicinese = 'Musica Ticinese',
    MusicaTedesca = 'Musica Tedesca',
    MusicaItaliana = 'Musica Italiana',
    SemiAcousticDuoTrioVoceEChitarra = 'Semi- & Acoustic duo/trio voce e chitarra',
    SemiAcousticDuoTrioVoceEPiano = 'Semi- & Acoustic duo/trio voce & piano',
    DuoTrioAcoustiqueInstrumental = 'Duo/trio acoustique instrumental',
    VoceEChitarraSolo = 'Voce e chitarra (solo)',
    VoceEPianoforteSolo = 'Voce e pianoforte (solo)',
    Alleinunterhalter = 'Alleinunterhalter',
    CantanteVoceFemminile = 'Cantante voce femminile',
    Fotografo = 'Fotografo',
    FotografoPerMatrimonio = 'Fotografo per matrimonio',
    Videomaker = 'Videomaker',
    VideomakerMatrimoni = 'Videomaker matrimoni',
    CastelliGonfiabili = 'Castelli gonfiabili',
    GonfiabiliPerFeste = 'Gonfiabili per feste',
    NoleggioDiCabineFotografiche = 'Noleggio di cabine fotografiche',
    Barista = 'Barista',
    Catering = 'Catering',
    FoodTrucks = 'Food Trucks',
    Sommelier = 'Sommelier',
    PianificatoreDiEventi = 'Pianificatore di eventi',
    WeddingPlanner = 'Wedding Planner',
    LimousinePerEventi = 'Limousine per eventi',
    BusPerEventi = 'Bus per eventi',
    SportEGiochi = 'Sport e giochi',
    EsperienzeNellaNatura = 'Esperienze nella natura',
    EventoPerTeam = 'Evento per team',
    Esperienza = 'Esperienza',
    Packages = 'Packages'
}

export type ArtistSubType = `${ArtistSubTypeEnum}`;

export const ArtistSubTypeValues: { [key in ArtistSubTypeEnum]: number } = {
    [ArtistSubTypeEnum.BigBand]: 1,
    [ArtistSubTypeEnum.SuonatoreDiSteelDrum]: 2,
    [ArtistSubTypeEnum.Karaoke]: 3,
    [ArtistSubTypeEnum.Originale]: 4,
    [ArtistSubTypeEnum.Cover]: 5,
    [ArtistSubTypeEnum.Tribute]: 6,
    [ArtistSubTypeEnum.OneManBand]: 7,
    [ArtistSubTypeEnum.Radio]: 8,
    [ArtistSubTypeEnum.Lounge]: 9,
    [ArtistSubTypeEnum.MusicaAcustica]: 10,
    [ArtistSubTypeEnum.GruppoACappella]: 11,
    [ArtistSubTypeEnum.Quartetto]: 12,
    [ArtistSubTypeEnum.TrioDarchi]: 13,
    [ArtistSubTypeEnum.Guggen]: 14,
    [ArtistSubTypeEnum.BrassBand]: 15,
    [ArtistSubTypeEnum.OrchestraDaCamera]: 16,
    [ArtistSubTypeEnum.DuoClassico]: 17,
    [ArtistSubTypeEnum.Orchestra]: 18,
    [ArtistSubTypeEnum.Coro]: 19,
    [ArtistSubTypeEnum.Percussionista]: 20,
    [ArtistSubTypeEnum.Sassofonista]: 21,
    [ArtistSubTypeEnum.Pianista]: 22,
    [ArtistSubTypeEnum.CantanteVoceMaschile]: 23,
    [ArtistSubTypeEnum.Violinista]: 24,
    [ArtistSubTypeEnum.Flautista]: 25,
    [ArtistSubTypeEnum.Chitarrista]: 26,
    [ArtistSubTypeEnum.Violoncellista]: 27,
    [ArtistSubTypeEnum.Vocalist]: 28,
    [ArtistSubTypeEnum.Tastierista]: 29,
    [ArtistSubTypeEnum.Organista]: 30,
    [ArtistSubTypeEnum.Crooner]: 31,
    [ArtistSubTypeEnum.Arpista]: 32,
    [ArtistSubTypeEnum.Rapper]: 33,
    [ArtistSubTypeEnum.Trombettista]: 34,
    [ArtistSubTypeEnum.Club]: 35,
    [ArtistSubTypeEnum.Clown]: 36,
    [ArtistSubTypeEnum.Comico]: 37,
    [ArtistSubTypeEnum.ScultoreDiPalloncini]: 38,
    [ArtistSubTypeEnum.FacePainter]: 39,
    [ArtistSubTypeEnum.Giocoliere]: 40,
    [ArtistSubTypeEnum.Walkacts]: 41,
    [ArtistSubTypeEnum.FireJuggler]: 42,
    [ArtistSubTypeEnum.Caricaturista]: 43,
    [ArtistSubTypeEnum.BabboNatale]: 44,
    [ArtistSubTypeEnum.BambolaVivente]: 45,
    [ArtistSubTypeEnum.Prestigiatore]: 46,
    [ArtistSubTypeEnum.Mentalista]: 47,
    [ArtistSubTypeEnum.MagiaPerBambini]: 48,
    [ArtistSubTypeEnum.Presentatore]: 49,
    [ArtistSubTypeEnum.Moderatore]: 50,
    [ArtistSubTypeEnum.AttoreAttrice]: 51,
    [ArtistSubTypeEnum.BallerinoBallerinaHula]: 54,
    [ArtistSubTypeEnum.GruppoDiDanza]: 55,
    [ArtistSubTypeEnum.BallerinoBallerinaCountry]: 56,
    [ArtistSubTypeEnum.BallerinoBallerinaHipHop]: 57,
    [ArtistSubTypeEnum.BallerinoBallerinaTipTap]: 58,
    [ArtistSubTypeEnum.BallerinoBallerinaFlamenco]: 59,
    [ArtistSubTypeEnum.BallerinoBallerinaTango]: 60,
    [ArtistSubTypeEnum.BallerinoBallerinaMusicaLatina]: 61,
    [ArtistSubTypeEnum.Vintage]: 62,
    [ArtistSubTypeEnum.DanzatriceDelVentre]: 63,
    [ArtistSubTypeEnum.Altro]: 64,
    [ArtistSubTypeEnum.Ventriloquo]: 65,
    [ArtistSubTypeEnum.Acrobati]: 66,
    [ArtistSubTypeEnum.Cornamusa]: 67,
    [ArtistSubTypeEnum.CornoDelleAlpi]: 68,
    [ArtistSubTypeEnum.Armonica]: 69,
    [ArtistSubTypeEnum.Corno]: 70,
    [ArtistSubTypeEnum.VJ]: 71,
    [ArtistSubTypeEnum.OratoreAtletica]: 72,
    [ArtistSubTypeEnum.OratoreBusiness]: 73,
    [ArtistSubTypeEnum.OratoreCelebrita]: 74,
    [ArtistSubTypeEnum.OratoreAziendale]: 75,
    [ArtistSubTypeEnum.Ispiratore]: 76,
    [ArtistSubTypeEnum.Motivatore]: 77,
    [ArtistSubTypeEnum.CommentatoreSportivo]: 78,
    [ArtistSubTypeEnum.Cabaret]: 79,
    [ArtistSubTypeEnum.Sosia]: 80,
    [ArtistSubTypeEnum.Mariachi]: 81,
    [ArtistSubTypeEnum.Percussioni]: 82,
    [ArtistSubTypeEnum.Legni]: 83,
    [ArtistSubTypeEnum.Duo]: 84,
    [ArtistSubTypeEnum.Trio]: 85,
    [ArtistSubTypeEnum.FlautoDiPan]: 86,
    [ArtistSubTypeEnum.PianoBar]: 87,
    [ArtistSubTypeEnum.Fisarmonica]: 88,
    [ArtistSubTypeEnum.BodyPainter]: 89,
    [ArtistSubTypeEnum.QuartettoDarchiESimili]: 90,
    [ArtistSubTypeEnum.PartyDJ]: 91,
    [ArtistSubTypeEnum.DJPerSottofondo]: 92,
    [ArtistSubTypeEnum.DJConStrumentiDalVivo]: 93,
    [ArtistSubTypeEnum.DJConCantante]: 94,
    [ArtistSubTypeEnum.DJConKaraoke]: 95,
    [ArtistSubTypeEnum.PopRockPartyband]: 96,
    [ArtistSubTypeEnum.SchlagerOldies]: 97,
    [ArtistSubTypeEnum.BandDiGalaOrchestraDaBallo]: 98,
    [ArtistSubTypeEnum.RockabillyPartyband]: 99,
    [ArtistSubTypeEnum.PartybandIrlandese]: 100,
    [ArtistSubTypeEnum.CountryPartyband]: 101,
    [ArtistSubTypeEnum.PartybandLatinoAmericana]: 102,
    [ArtistSubTypeEnum.JazzBand]: 103,
    [ArtistSubTypeEnum.VolkstumlicheMusik]: 104,
    [ArtistSubTypeEnum.MusicaTicinese]: 105,
    [ArtistSubTypeEnum.MusicaTedesca]: 106,
    [ArtistSubTypeEnum.MusicaItaliana]: 107,
    [ArtistSubTypeEnum.SemiAcousticDuoTrioVoceEChitarra]: 108,
    [ArtistSubTypeEnum.SemiAcousticDuoTrioVoceEPiano]: 109,
    [ArtistSubTypeEnum.DuoTrioAcoustiqueInstrumental]: 110,
    [ArtistSubTypeEnum.VoceEChitarraSolo]: 111,
    [ArtistSubTypeEnum.VoceEPianoforteSolo]: 112,
    [ArtistSubTypeEnum.Alleinunterhalter]: 113,
    [ArtistSubTypeEnum.CantanteVoceFemminile]: 114,
    [ArtistSubTypeEnum.Fotografo]: 115,
    [ArtistSubTypeEnum.FotografoPerMatrimonio]: 116,
    [ArtistSubTypeEnum.Videomaker]: 118,
    [ArtistSubTypeEnum.VideomakerMatrimoni]: 119,
    [ArtistSubTypeEnum.CastelliGonfiabili]: 120,
    [ArtistSubTypeEnum.GonfiabiliPerFeste]: 121,
    [ArtistSubTypeEnum.NoleggioDiCabineFotografiche]: 122,
    [ArtistSubTypeEnum.Barista]: 123,
    [ArtistSubTypeEnum.Catering]: 124,
    [ArtistSubTypeEnum.FoodTrucks]: 125,
    [ArtistSubTypeEnum.Sommelier]: 126,
    [ArtistSubTypeEnum.PianificatoreDiEventi]: 127,
    [ArtistSubTypeEnum.WeddingPlanner]: 128,
    [ArtistSubTypeEnum.LimousinePerEventi]: 129,
    [ArtistSubTypeEnum.BusPerEventi]: 130,
    [ArtistSubTypeEnum.SportEGiochi]: 131,
    [ArtistSubTypeEnum.EsperienzeNellaNatura]: 132,
    [ArtistSubTypeEnum.EventoPerTeam]: 133,
    [ArtistSubTypeEnum.Esperienza]: 134,
    [ArtistSubTypeEnum.Packages]: 135
};

export enum ArtistGenreEnum {
    Pop = 'Pop',
    Rock = 'Rock',
    Electro = 'Electro',
    RnB = 'R&B',
    Metal = 'Metal',
    HouseTechno = 'House/Techno',
    HipHop = 'Hip Hop',
    Punk = 'Punk',
    DiscoDance = 'Disco Dance',
    Rap = 'Rap',
    Alternative = 'Alternative',
    Jazz = 'Jazz',
    Latin = 'Latin',
    Folk = 'Folk',
    Classical = 'Classical',
    Reggae = 'Reggae',
    Funk = 'Funk',
    ChristianGospel = 'Christian/Gospel',
    Country = 'Country',
    Ska = 'Ska',
    WorldMusic = 'World Music',
    Blues = 'Blues',
    Other = 'Other',
    Lounge = 'Lounge',
    Soul = 'Soul',
    Swing = 'Swing',
    Rockabilly = 'Rockabilly',
    Tanzmusik = 'Tanzmusik',
    VolkstumlicheMusik = 'Volkstümliche Musik',
    Schlager = 'Schlager',
    Oldiebands = 'Oldiebands',
    Celtic = 'Celtic',
    Irish = 'Irish',
    Twenties = '20s',
    Thirties = '30s',
    Forties = '40s',
    Fifties = '50s',
    Sixties = '60s',
    Seventies = '70s',
    Eighties = '80s',
    Nineties = '90s',
    African = 'African',
    Ambient = 'Ambient',
    Flamenco = 'Flamenco',
    Fusion = 'Fusion',
    Greek = 'Greek',
    Groove = 'Groove',
    Grunge = 'Grunge',
    Gypsy = 'Gypsy',
    Hawaiian = 'Hawaiian',
    HonkyTonk = 'Honky Tonk',
    Indie = 'Indie',
    Industrial = 'Industrial',
    Italian = 'Italian',
    Jam = 'Jam',
    MiddleEastern = 'Middle Eastern',
    NewAge = 'New Age',
    Polka = 'Polka',
    Ragtime = 'Ragtime',
    SalsaMerengue = 'Salsa/Merengue',
    SouthernRock = 'Southern Rock',
    SurfBeach = 'Surf/Beach',
    Bluegrass = 'Bluegrass',
    Brazilian = 'Brazilian',
    Carribean = 'Carribean',
    Cuban = 'Cuban',
    Tango = 'Tango',
    Christmas = 'Christmas',
    Meditational = 'Meditational',
    Opera = 'Opera',
    ChamberMusic = 'Chamber Music',
    KidsMusic = 'Kids Music',
    Ticinese = 'Ticinese',
    Jodel = 'Jodel',
    HardRock = 'Hard Rock',
    Mundart = 'Mundart'
}

export type ArtistGenre = `${ArtistGenreEnum}`;

export const ArtistGenreMapping: { [key in ArtistGenreEnum]: number } = {
    [ArtistGenreEnum.Pop]: 1,
    [ArtistGenreEnum.Rock]: 2,
    [ArtistGenreEnum.Electro]: 3,
    [ArtistGenreEnum.RnB]: 4,
    [ArtistGenreEnum.Metal]: 5,
    [ArtistGenreEnum.HouseTechno]: 6,
    [ArtistGenreEnum.HipHop]: 7,
    [ArtistGenreEnum.Punk]: 8,
    [ArtistGenreEnum.DiscoDance]: 9,
    [ArtistGenreEnum.Rap]: 10,
    [ArtistGenreEnum.Alternative]: 11,
    [ArtistGenreEnum.Jazz]: 12,
    [ArtistGenreEnum.Latin]: 13,
    [ArtistGenreEnum.Folk]: 14,
    [ArtistGenreEnum.Classical]: 15,
    [ArtistGenreEnum.Reggae]: 16,
    [ArtistGenreEnum.Funk]: 17,
    [ArtistGenreEnum.ChristianGospel]: 18,
    [ArtistGenreEnum.Country]: 19,
    [ArtistGenreEnum.Ska]: 20,
    [ArtistGenreEnum.WorldMusic]: 21,
    [ArtistGenreEnum.Blues]: 22,
    [ArtistGenreEnum.Other]: 23,
    [ArtistGenreEnum.Lounge]: 24,
    [ArtistGenreEnum.Soul]: 25,
    [ArtistGenreEnum.Swing]: 26,
    [ArtistGenreEnum.Rockabilly]: 27,
    [ArtistGenreEnum.Tanzmusik]: 28,
    [ArtistGenreEnum.VolkstumlicheMusik]: 29,
    [ArtistGenreEnum.Schlager]: 30,
    [ArtistGenreEnum.Oldiebands]: 31,
    [ArtistGenreEnum.Celtic]: 32,
    [ArtistGenreEnum.Irish]: 33,
    [ArtistGenreEnum.Twenties]: 34,
    [ArtistGenreEnum.Thirties]: 35,
    [ArtistGenreEnum.Forties]: 36,
    [ArtistGenreEnum.Fifties]: 37,
    [ArtistGenreEnum.Sixties]: 38,
    [ArtistGenreEnum.Seventies]: 39,
    [ArtistGenreEnum.Eighties]: 40,
    [ArtistGenreEnum.Nineties]: 41,
    [ArtistGenreEnum.African]: 42,
    [ArtistGenreEnum.Ambient]: 43,
    [ArtistGenreEnum.Flamenco]: 44,
    [ArtistGenreEnum.Fusion]: 45,
    [ArtistGenreEnum.Greek]: 46,
    [ArtistGenreEnum.Groove]: 47,
    [ArtistGenreEnum.Grunge]: 48,
    [ArtistGenreEnum.Gypsy]: 49,
    [ArtistGenreEnum.Hawaiian]: 50,
    [ArtistGenreEnum.HonkyTonk]: 51,
    [ArtistGenreEnum.Indie]: 52,
    [ArtistGenreEnum.Industrial]: 53,
    [ArtistGenreEnum.Italian]: 54,
    [ArtistGenreEnum.Jam]: 55,
    [ArtistGenreEnum.MiddleEastern]: 56,
    [ArtistGenreEnum.NewAge]: 58,
    [ArtistGenreEnum.Polka]: 59,
    [ArtistGenreEnum.Ragtime]: 60,
    [ArtistGenreEnum.SalsaMerengue]: 61,
    [ArtistGenreEnum.SouthernRock]: 62,
    [ArtistGenreEnum.SurfBeach]: 63,
    [ArtistGenreEnum.Bluegrass]: 64,
    [ArtistGenreEnum.Brazilian]: 65,
    [ArtistGenreEnum.Carribean]: 66,
    [ArtistGenreEnum.Cuban]: 67,
    [ArtistGenreEnum.Tango]: 68,
    [ArtistGenreEnum.Christmas]: 69,
    [ArtistGenreEnum.Meditational]: 70,
    [ArtistGenreEnum.Opera]: 71,
    [ArtistGenreEnum.ChamberMusic]: 72,
    [ArtistGenreEnum.KidsMusic]: 73,
    [ArtistGenreEnum.Ticinese]: 74,
    [ArtistGenreEnum.Jodel]: 75,
    [ArtistGenreEnum.HardRock]: 76,
    [ArtistGenreEnum.Mundart]: 77
};

export enum FilterType {
    LANGUAGE = 'LANGUAGE',
    SHOW_TYPE = 'SHOW_TYPE',
    ARTIST_TYPE = 'ARTIST_TYPE',
    ARTIST_SUB_TYPE = 'ARTIST_SUB_TYPE',
    ARTIST_GENRE = 'ARTIST_GENRE'
}

export type LanguageFilter = {
	f: FilterType.LANGUAGE;
	k: AllowedLanguages;
    v: AllowedLanguages;
    i: boolean;
};

export type ShowTypeFilter = {
	f: FilterType.SHOW_TYPE;
	k: number;
    v: ShowTypeEnum;
    i: boolean;
};

export type ArtistTypeFilter = {
	f: FilterType.ARTIST_TYPE;
	k: number;
    v: ArtistTypeEnum;
    i: boolean;
};

export type ArtistSubTypeFilter = {
	f: FilterType.ARTIST_SUB_TYPE;
	k: number;
    v: ArtistSubTypeEnum;
    i: boolean;
};

export type ArtistGenreFilter = {
	f: FilterType.ARTIST_GENRE;
	k: number;
    v: ArtistGenreEnum;
    i: boolean;
};

export type Filter = LanguageFilter | ShowTypeFilter | ArtistTypeFilter | ArtistSubTypeFilter | ArtistGenreFilter;